### ISSUE TITLE
Info section

### ISSUE THREAD

**Issue by mpagels** [mpagels/kindrgrowth#1]
## Value statement - a requirement, not a solution
As a **(user)** 
I need **(a section, with a header and tags)** 
so that **(I can see useful information)** 

## Description (Text, Scribble, Wireframe, Design)
![grafik](https://user-images.githubusercontent.com/54703643/164472059-9fd60252-e013-4a43-bd63-a349195559eb.png)

![grafik](https://user-images.githubusercontent.com/54703643/164472396-884e602e-f3e4-4e3f-9cb0-dbc07a5874d2.png)

## Acceptance criteria
- [ ] the component renders a header
- [ ] the compnent renders a list of labels
- [ ] a label should have this color #8972q9

## Tasks
- [ ] research again how to write a list in html
- [ ] research express

## Size
(small)
