### ISSUE TITLE
Spurt counter

### ISSUE THREAD

**Issue by mpagels** [mpagels/kindrgrowth#2]
## Value statement - a requirement, not a solution
As a **user** 
I need **a spurt counter** 
so that **I can move through the spurts and show different data** 

## Description (Text, Scribble, Wireframe, Design)
The user need to move through the spurts.

![grafik](https://user-images.githubusercontent.com/54703643/164474153-f2b365d5-402d-44c6-971f-82bd9d260f62.png)

![grafik](https://user-images.githubusercontent.com/54703643/164474252-98067109-898c-4d23-bb50-a3574484e67a.png)

![grafik](https://user-images.githubusercontent.com/54703643/164474290-e3326185-10a8-4e40-bb5e-c2aac2b43bc6.png)

![grafik](https://user-images.githubusercontent.com/54703643/164474335-d545a4ce-c773-48c6-81e2-56e31c4c94d4.png)

## Acceptance criteria
- [ ] when the user comes to the page, the counter should start at `1`
- [ ] it should show the date range (ex. 25.12 - 27.01)
- [ ] the left symbol should display the week
- [ ] the right symbol should display the date of tip of the iceberg
- [ ] if the user clicks the right arrow button, the next data should load and display
- [ ] the number adds up to 2
- [ ] the range date changes
- [ ] and the symbols labels changes as well

## Tasks
- [ ] #3

## Size
(large)
